-- Skema dasar projectB.
--
-- Berkas ini membuat seluruh tabel inti dari nol. Sebelum ada berkas ini,
-- scripts/sql hanya berisi migrasi inkremental -- semuanya mengubah tabel
-- yang sudah ada -- sehingga deployment baru tidak bisa dibangun dari repo
-- saja. Itu yang bikin carlynk.id berdiri dengan database kosong.
--
-- Dihasilkan dari SHOW CREATE TABLE, struktur saja tanpa data.
-- Semua pakai IF NOT EXISTS, jadi aman dijalankan ulang di database yang
-- sudah terisi.
--
-- Urutannya menyusul relasi antar tabel, jadi pemeriksaan foreign key
-- dimatikan selama impor.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `admin_impersonation_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `admin_user_id` bigint unsigned NOT NULL,
  `target_user_id` bigint unsigned NOT NULL,
  `selector` char(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hashed_validator` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `started_at` datetime NOT NULL,
  `expires_at` datetime NOT NULL,
  `last_used_at` datetime DEFAULT NULL,
  `ended_at` datetime DEFAULT NULL,
  `ended_reason` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_admin_impersonation_selector` (`selector`),
  KEY `idx_admin_impersonation_admin_user_id` (`admin_user_id`),
  KEY `idx_admin_impersonation_target_user_id` (`target_user_id`),
  KEY `idx_admin_impersonation_expires_at` (`expires_at`),
  CONSTRAINT `fk_admin_impersonation_admin_user` FOREIGN KEY (`admin_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_admin_impersonation_target_user` FOREIGN KEY (`target_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `affiliate_click_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `affiliate_id` bigint unsigned NOT NULL,
  `clicked_at` datetime NOT NULL,
  `ip_address` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `landing_url` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_affiliate_click_logs_affiliate_id` (`affiliate_id`),
  KEY `idx_affiliate_click_logs_clicked_at` (`clicked_at`),
  CONSTRAINT `fk_affiliate_click_logs_affiliate_id` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliates` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `affiliate_commission_ledgers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `affiliate_id` bigint unsigned NOT NULL,
  `affiliate_user_id` bigint unsigned DEFAULT NULL,
  `transaction_id` bigint unsigned DEFAULT NULL,
  `seller_user_id` bigint unsigned DEFAULT NULL,
  `showroom_id` bigint unsigned DEFAULT NULL,
  `buyer_user_id` bigint unsigned DEFAULT NULL,
  `source_type` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_id` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entry_type` enum('accrual','adjustment','payout') COLLATE utf8mb4_unicode_ci NOT NULL,
  `rule_source` enum('global','car_override') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `commission_type` enum('percent','flat') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `commission_value_snapshot` decimal(15,2) DEFAULT NULL,
  `base_amount` decimal(15,2) DEFAULT NULL,
  `commission_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
  `amount` decimal(15,2) NOT NULL,
  `currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'IDR',
  `ledger_status` enum('pending','accrued','paid_out','voided') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `settlement_id` bigint unsigned DEFAULT NULL,
  `finality_event` enum('paid') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accrued_at` datetime DEFAULT NULL,
  `pending_at` datetime DEFAULT NULL,
  `paid_out_at` datetime DEFAULT NULL,
  `voided_at` datetime DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_affiliate_commission_ledgers_accrual_source` (`transaction_id`,`affiliate_id`,`source_type`,`source_id`),
  KEY `idx_affiliate_commission_ledgers_affiliate_id` (`affiliate_id`),
  KEY `idx_affiliate_commission_ledgers_transaction_id` (`transaction_id`),
  KEY `idx_affiliate_commission_ledgers_seller_user_id` (`seller_user_id`),
  KEY `idx_affiliate_commission_ledgers_showroom_id` (`showroom_id`),
  KEY `idx_affiliate_commission_ledgers_status` (`ledger_status`),
  KEY `idx_affiliate_commission_ledgers_affiliate_user_id` (`affiliate_user_id`),
  KEY `idx_affiliate_commission_ledgers_settlement_id` (`settlement_id`),
  KEY `idx_affiliate_commission_ledgers_source` (`source_type`,`source_id`),
  KEY `fk_affiliate_commission_ledgers_buyer` (`buyer_user_id`),
  CONSTRAINT `fk_affiliate_commission_ledgers_affiliate_id` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliates` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_affiliate_commission_ledgers_affiliate_user` FOREIGN KEY (`affiliate_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_affiliate_commission_ledgers_buyer` FOREIGN KEY (`buyer_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_affiliate_commission_ledgers_seller` FOREIGN KEY (`seller_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_affiliate_commission_ledgers_settlement` FOREIGN KEY (`settlement_id`) REFERENCES `affiliate_settlement_batches` (`id`),
  CONSTRAINT `fk_affiliate_commission_ledgers_showroom` FOREIGN KEY (`showroom_id`) REFERENCES `showrooms` (`id`),
  CONSTRAINT `fk_affiliate_commission_ledgers_transaction_id` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `affiliate_commission_rules` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `seller_user_id` bigint unsigned NOT NULL,
  `car_id` bigint unsigned DEFAULT NULL,
  `commission_type` enum('percent','flat') COLLATE utf8mb4_unicode_ci NOT NULL,
  `commission_percent` decimal(5,2) NOT NULL DEFAULT '0.00',
  `commission_flat` decimal(15,2) NOT NULL DEFAULT '0.00',
  `status` enum('active','inactive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_affiliate_commission_rules_seller_user_id` (`seller_user_id`),
  KEY `idx_affiliate_commission_rules_car_id` (`car_id`),
  KEY `idx_affiliate_commission_rules_status` (`status`),
  CONSTRAINT `fk_affiliate_commission_rules_car` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`),
  CONSTRAINT `fk_affiliate_commission_rules_seller` FOREIGN KEY (`seller_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `affiliate_settlement_batches` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `settlement_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `affiliate_id` bigint unsigned NOT NULL,
  `affiliate_user_id` bigint unsigned DEFAULT NULL,
  `requested_amount` decimal(15,2) NOT NULL,
  `currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'IDR',
  `ledger_count` int NOT NULL DEFAULT '0',
  `status` enum('pending','settled','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `payment_method` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_reference` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_note` text COLLATE utf8mb4_unicode_ci,
  `proof_file_url` text COLLATE utf8mb4_unicode_ci,
  `period_start` date DEFAULT NULL,
  `period_end` date DEFAULT NULL,
  `requested_by` bigint unsigned DEFAULT NULL,
  `approved_by` bigint unsigned DEFAULT NULL,
  `paid_by` bigint unsigned DEFAULT NULL,
  `cancelled_by` bigint unsigned DEFAULT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `requested_at` datetime NOT NULL,
  `settled_at` datetime DEFAULT NULL,
  `cancelled_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_affiliate_settlement_batches_code` (`settlement_code`),
  KEY `idx_affiliate_settlement_batches_affiliate_id` (`affiliate_id`),
  KEY `idx_affiliate_settlement_batches_status` (`status`),
  KEY `idx_affiliate_settlement_batches_requested_at` (`requested_at`),
  KEY `idx_affiliate_settlement_batches_affiliate_user_id` (`affiliate_user_id`),
  KEY `fk_affiliate_settlement_batches_requested_by` (`requested_by`),
  KEY `fk_affiliate_settlement_batches_approved_by` (`approved_by`),
  KEY `fk_affiliate_settlement_batches_paid_by` (`paid_by`),
  KEY `fk_affiliate_settlement_batches_cancelled_by` (`cancelled_by`),
  CONSTRAINT `fk_affiliate_settlement_batches_affiliate` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliates` (`id`),
  CONSTRAINT `fk_affiliate_settlement_batches_affiliate_user` FOREIGN KEY (`affiliate_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_affiliate_settlement_batches_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_affiliate_settlement_batches_cancelled_by` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_affiliate_settlement_batches_paid_by` FOREIGN KEY (`paid_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_affiliate_settlement_batches_requested_by` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `affiliate_settlement_histories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `settlement_id` bigint unsigned NOT NULL,
  `from_status` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `to_status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `note` text COLLATE utf8mb4_unicode_ci,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_affiliate_settlement_histories_settlement_id` (`settlement_id`),
  KEY `idx_affiliate_settlement_histories_actor_user_id` (`actor_user_id`),
  CONSTRAINT `fk_affiliate_settlement_histories_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_affiliate_settlement_histories_settlement` FOREIGN KEY (`settlement_id`) REFERENCES `affiliate_settlement_batches` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `affiliate_settlement_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `settlement_batch_id` bigint unsigned NOT NULL,
  `ledger_id` bigint unsigned NOT NULL,
  `amount_snapshot` decimal(15,2) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_affiliate_settlement_items_ledger_id` (`ledger_id`),
  KEY `idx_affiliate_settlement_items_batch_id` (`settlement_batch_id`),
  CONSTRAINT `fk_affiliate_settlement_items_batch` FOREIGN KEY (`settlement_batch_id`) REFERENCES `affiliate_settlement_batches` (`id`),
  CONSTRAINT `fk_affiliate_settlement_items_ledger` FOREIGN KEY (`ledger_id`) REFERENCES `affiliate_commission_ledgers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `affiliates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `seller_user_id` bigint unsigned NOT NULL,
  `referral_code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `commission_type` enum('percent','flat') COLLATE utf8mb4_unicode_ci NOT NULL,
  `commission_percent` decimal(5,2) NOT NULL DEFAULT '0.00',
  `commission_flat` decimal(15,2) NOT NULL DEFAULT '0.00',
  `total_clicks` int NOT NULL DEFAULT '0',
  `total_transactions` int NOT NULL DEFAULT '0',
  `total_commission` decimal(15,2) NOT NULL DEFAULT '0.00',
  `status` enum('active','inactive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_affiliates_referral_code` (`referral_code`),
  KEY `idx_affiliates_user_id` (`user_id`),
  KEY `idx_affiliates_seller_user_id` (`seller_user_id`),
  KEY `idx_affiliates_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_affiliates_seller_user_id` FOREIGN KEY (`seller_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_affiliates_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `api_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `resource_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `version_number` int NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_api_versions_resource_name` (`resource_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `car_favorites` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `car_id` bigint unsigned NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_car_favorites_user_car` (`user_id`,`car_id`),
  KEY `idx_car_favorites_user_deleted` (`user_id`,`deleted_at`),
  KEY `idx_car_favorites_car` (`car_id`),
  CONSTRAINT `fk_car_favorites_car` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_car_favorites_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `car_images` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `car_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `file_path` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `mime_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sort_order` int NOT NULL DEFAULT '0',
  `is_cover` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_car_images_car_id` (`car_id`),
  KEY `idx_car_images_user_id` (`user_id`),
  KEY `idx_car_images_is_cover` (`is_cover`),
  KEY `idx_car_images_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_car_images_car_id` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_car_images_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cars` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `seller_user_id` bigint unsigned NOT NULL,
  `showroom_id` bigint unsigned DEFAULT NULL,
  `listing_status` enum('draft','published','reserved','sold','archived') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `stock` int NOT NULL DEFAULT '1',
  `license_plate_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `brand_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `model_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sub_model_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `primary_color` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `secondary_color` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `color_variation` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `document_type` enum('new','old') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_date` date DEFAULT NULL,
  `transmission` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `engine_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `chassis_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location_name` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `engine_capacity_cc` int DEFAULT NULL,
  `mileage_km` int DEFAULT NULL,
  `seat_count` int DEFAULT NULL,
  `previous_owner_count` int DEFAULT NULL,
  `has_service_book` tinyint(1) NOT NULL DEFAULT '0',
  `key_count` int NOT NULL DEFAULT '1',
  `description` text COLLATE utf8mb4_unicode_ci,
  `youtube_url` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price_cash` bigint DEFAULT NULL,
  `price_discount` bigint DEFAULT NULL,
  `price_credit` bigint DEFAULT NULL,
  `dp_amount` bigint DEFAULT NULL,
  `inspection_summary_status` enum('not_checked','partial','completed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'not_checked',
  `published_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cars_seller_user_id` (`seller_user_id`),
  KEY `idx_cars_showroom_id` (`showroom_id`),
  KEY `idx_cars_listing_status` (`listing_status`),
  KEY `idx_cars_brand_name` (`brand_name`),
  KEY `idx_cars_model_name` (`model_name`),
  KEY `idx_cars_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_cars_seller_user_id` FOREIGN KEY (`seller_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_cars_showroom_id` FOREIGN KEY (`showroom_id`) REFERENCES `showrooms` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inspection_report_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `inspection_report_id` bigint unsigned NOT NULL,
  `template_id` bigint unsigned NOT NULL,
  `item_name_snapshot` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `result_status` enum('good','fair','bad','not_available') COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_inspection_report_items_report_id` (`inspection_report_id`),
  KEY `idx_inspection_report_items_template_id` (`template_id`),
  CONSTRAINT `fk_inspection_report_items_report_id` FOREIGN KEY (`inspection_report_id`) REFERENCES `inspection_reports` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_inspection_report_items_template_id` FOREIGN KEY (`template_id`) REFERENCES `inspection_templates` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inspection_reports` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `car_id` bigint unsigned NOT NULL,
  `inspector_user_id` bigint unsigned NOT NULL,
  `report_status` enum('draft','completed','published') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `summary_notes` text COLLATE utf8mb4_unicode_ci,
  `inspected_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_inspection_reports_car_id` (`car_id`),
  KEY `idx_inspection_reports_inspector_user_id` (`inspector_user_id`),
  KEY `idx_inspection_reports_report_status` (`report_status`),
  KEY `idx_inspection_reports_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_inspection_reports_car_id` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_inspection_reports_inspector_user_id` FOREIGN KEY (`inspector_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inspection_templates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `category_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `item_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `sort_order` int NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inspection_templates_category_item` (`category_name`,`item_name`),
  KEY `idx_inspection_templates_category_name` (`category_name`),
  KEY `idx_inspection_templates_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `master_data` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `master_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `data_json` json NOT NULL,
  `api_version_id` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_master_data_master_key` (`master_key`),
  KEY `idx_master_data_api_version_id` (`api_version_id`),
  KEY `idx_master_data_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_master_data_api_version_id` FOREIGN KEY (`api_version_id`) REFERENCES `api_versions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `role` enum('seller','buyer','affiliate_admin','admin') COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` varchar(600) COLLATE utf8mb4_unicode_ci NOT NULL,
  `data_json` longtext COLLATE utf8mb4_unicode_ci,
  `link_url` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icon_key` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `priority` enum('low','normal','high') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  `source_type` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_id` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT '0',
  `read_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_user_role_created` (`user_id`,`role`,`created_at`,`id`),
  KEY `idx_notifications_user_role_read` (`user_id`,`role`,`is_read`),
  KEY `idx_notifications_type` (`type`),
  KEY `idx_notifications_source` (`source_type`,`source_id`),
  KEY `idx_notifications_actor` (`actor_user_id`),
  CONSTRAINT `fk_notifications_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `schema_migrations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `migration_name` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `checksum` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `applied_at` datetime NOT NULL,
  `execution_ms` int unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `schema_migrations_name_unique` (`migration_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `showrooms` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `slug` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(225) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone_number` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_account_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_account_name` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icon_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tab_title` varchar(70) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_showrooms_user_id` (`user_id`),
  UNIQUE KEY `showrooms_slug_unique` (`slug`),
  KEY `idx_showrooms_deleted_at` (`deleted_at`),
  KEY `idx_showrooms_city_name` (`city_name`),
  CONSTRAINT `fk_showrooms_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sliders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `subtitle` varchar(220) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `body_text` text COLLATE utf8mb4_unicode_ci,
  `html_content` text COLLATE utf8mb4_unicode_ci,
  `image_url` text COLLATE utf8mb4_unicode_ci,
  `image_alt` varchar(180) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cta_text` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cta_url` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `position_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'landing_hero',
  `template_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'elegant_gradient',
  `animation_key` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'fade',
  `sort_order` int NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `start_at` datetime DEFAULT NULL,
  `end_at` datetime DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sliders_code_unique` (`code`),
  KEY `sliders_position_active_order_idx` (`position_key`,`is_active`,`sort_order`),
  KEY `sliders_template_idx` (`template_key`),
  KEY `sliders_schedule_idx` (`start_at`,`end_at`),
  KEY `sliders_created_by_idx` (`created_by`),
  KEY `sliders_updated_by_idx` (`updated_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `transaction_fulfillment_checklist_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `transaction_id` bigint unsigned NOT NULL,
  `checklist_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `label` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_required` tinyint(1) NOT NULL DEFAULT '1',
  `is_completed` tinyint(1) NOT NULL DEFAULT '0',
  `completed_at` datetime DEFAULT NULL,
  `completed_by_user_id` bigint unsigned DEFAULT NULL,
  `notes` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sort_order` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_transaction_fulfillment_item` (`transaction_id`,`checklist_key`),
  KEY `idx_transaction_fulfillment_transaction` (`transaction_id`),
  KEY `idx_transaction_fulfillment_completed` (`is_completed`),
  KEY `fk_transaction_fulfillment_completed_by` (`completed_by_user_id`),
  CONSTRAINT `fk_transaction_fulfillment_completed_by` FOREIGN KEY (`completed_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_transaction_fulfillment_transaction` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `transaction_payment_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `transaction_id` bigint unsigned NOT NULL,
  `provider_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'midtrans',
  `provider_order_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider_transaction_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_method` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transaction_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gross_amount` bigint DEFAULT NULL,
  `payload_request_json` longtext COLLATE utf8mb4_unicode_ci,
  `payload_response_json` longtext COLLATE utf8mb4_unicode_ci,
  `payload_callback_json` longtext COLLATE utf8mb4_unicode_ci,
  `logged_at` datetime NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_transaction_payment_logs_transaction_id` (`transaction_id`),
  KEY `idx_transaction_payment_logs_provider_order_id` (`provider_order_id`),
  CONSTRAINT `fk_transaction_payment_logs_transaction_id` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `transaction_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `buyer_user_id` bigint unsigned NOT NULL,
  `seller_user_id` bigint unsigned NOT NULL,
  `car_id` bigint unsigned NOT NULL,
  `affiliate_id` bigint unsigned DEFAULT NULL,
  `affiliate_referral_code_snapshot` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `car_price` bigint NOT NULL,
  `payment_type` enum('dp','full') COLLATE utf8mb4_unicode_ci NOT NULL,
  `dp_amount` bigint DEFAULT NULL,
  `remaining_amount` bigint DEFAULT NULL,
  `transaction_status` enum('pending_payment','dp_paid','paid','completed','expired','cancelled','returned') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending_payment',
  `midtrans_order_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `midtrans_token` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `midtrans_redirect_url` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `returned_at` datetime DEFAULT NULL,
  `return_reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_transactions_transaction_code` (`transaction_code`),
  KEY `idx_transactions_buyer_user_id` (`buyer_user_id`),
  KEY `idx_transactions_seller_user_id` (`seller_user_id`),
  KEY `idx_transactions_car_id` (`car_id`),
  KEY `idx_transactions_transaction_status` (`transaction_status`),
  KEY `idx_transactions_midtrans_order_id` (`midtrans_order_id`),
  KEY `idx_transactions_deleted_at` (`deleted_at`),
  KEY `idx_transactions_affiliate_id` (`affiliate_id`),
  CONSTRAINT `fk_transactions_affiliate` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliates` (`id`),
  CONSTRAINT `fk_transactions_buyer_user_id` FOREIGN KEY (`buyer_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_transactions_car_id` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_transactions_seller_user_id` FOREIGN KEY (`seller_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_auth_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `selector` char(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hashed_validator` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `expires_at` datetime NOT NULL,
  `last_used_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `revoked_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_auth_tokens_selector` (`selector`),
  KEY `idx_user_auth_tokens_user_id` (`user_id`),
  KEY `idx_user_auth_tokens_expires_at` (`expires_at`),
  KEY `idx_user_auth_tokens_revoked_at` (`revoked_at`),
  CONSTRAINT `fk_user_auth_tokens_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_oauth_identities` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `provider` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider_user_id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider_email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar_url` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_oauth_provider_user` (`provider`,`provider_user_id`),
  UNIQUE KEY `uq_user_oauth_user_provider` (`user_id`,`provider`),
  KEY `idx_user_oauth_user_id` (`user_id`),
  KEY `idx_user_oauth_provider_email` (`provider`,`provider_email`),
  CONSTRAINT `fk_user_oauth_identities_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `role` enum('seller','buyer','affiliate_admin','admin','super_admin') COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone_number` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `account_status` enum('pending','active','suspended') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `otp_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `otp_expires_at` datetime DEFAULT NULL,
  `security_key` text COLLATE utf8mb4_unicode_ci,
  `is_approved` tinyint(1) NOT NULL DEFAULT '0',
  `home_showroom_id` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_email` (`email`),
  KEY `idx_users_role` (`role`),
  KEY `idx_users_account_status` (`account_status`),
  KEY `idx_users_deleted_at` (`deleted_at`),
  KEY `idx_users_home_showroom_id` (`home_showroom_id`),
  CONSTRAINT `fk_users_home_showroom_id` FOREIGN KEY (`home_showroom_id`) REFERENCES `showrooms` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
